import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:latlong2/latlong.dart';

/// The outline of the Diocese of Cleveland — its eight counties — used to tell
/// a user that where they're standing is not the area this app covers.
///
/// This replaced a "nearest parish is more than N miles away" heuristic, which
/// no threshold could make honest: neighbouring dioceses run right up against
/// ours (Stow is ours; Kent, five miles away, is Youngstown), while rural
/// corners of our own counties are 25+ miles from the nearest parish we list.
///
/// The polygons ship as a 2.4 KB asset generated by
/// `tool/gen_diocese_boundary.py` from US Census county boundaries, so the
/// check is exact, offline, and costs no reverse-geocoding round trip.
class DioceseBoundary {
  static const _assetPath = 'assets/data/diocese_boundary.json';

  /// One simplified ring per county, each a closed list of points.
  List<List<LatLng>>? _polygons;

  /// Bounding box over every polygon — rejects the far-away case (which is
  /// most of the planet) without walking a single edge.
  double _minLat = 0, _maxLat = 0, _minLon = 0, _maxLon = 0;

  bool get isLoaded => _polygons != null;

  /// Parse the bundled outline. Called once at startup; safe to call again.
  Future<void> load() async {
    if (_polygons != null) return;
    try {
      final raw = json.decode(await rootBundle.loadString(_assetPath));
      final polygons = <List<LatLng>>[];
      for (final polygon in raw['polygons'] as List) {
        polygons.add([
          for (final point in polygon as List)
            LatLng((point[0] as num).toDouble(), (point[1] as num).toDouble()),
        ]);
      }
      if (polygons.isEmpty) return;

      _minLat = _minLon = double.infinity;
      _maxLat = _maxLon = double.negativeInfinity;
      for (final polygon in polygons) {
        for (final point in polygon) {
          if (point.latitude < _minLat) _minLat = point.latitude;
          if (point.latitude > _maxLat) _maxLat = point.latitude;
          if (point.longitude < _minLon) _minLon = point.longitude;
          if (point.longitude > _maxLon) _maxLon = point.longitude;
        }
      }
      _polygons = polygons;
    } catch (e) {
      // Callers fall back to the distance rule when the outline is missing —
      // better a rough answer than a crash on a bundling mistake.
      debugPrint('DioceseBoundary: $e');
    }
  }

  /// Whether [point] falls inside the diocese, or null if the outline hasn't
  /// loaded. Null is deliberately not "outside": we don't tell someone they're
  /// out of the area on the strength of an asset we failed to read.
  bool? contains(LatLng point) {
    final polygons = _polygons;
    if (polygons == null) return null;
    if (point.latitude < _minLat ||
        point.latitude > _maxLat ||
        point.longitude < _minLon ||
        point.longitude > _maxLon) {
      return false;
    }
    for (final polygon in polygons) {
      if (_ringContains(polygon, point)) return true;
    }
    return false;
  }

  /// Standard ray casting: count the ring edges a due-west ray crosses.
  static bool _ringContains(List<LatLng> ring, LatLng point) {
    var inside = false;
    for (var i = 0, j = ring.length - 1; i < ring.length; j = i++) {
      final a = ring[i];
      final b = ring[j];
      if ((a.latitude > point.latitude) != (b.latitude > point.latitude)) {
        final crossing = (b.longitude - a.longitude) *
                (point.latitude - a.latitude) /
                (b.latitude - a.latitude) +
            a.longitude;
        if (point.longitude < crossing) inside = !inside;
      }
    }
    return inside;
  }
}

/// Shared instance — the outline is immutable, so one parse serves the app.
final dioceseBoundary = DioceseBoundary();
