#!/usr/bin/env python3
"""Generate assets/data/diocese_boundary.json — the Diocese of Cleveland's
outline, used to tell a user they're outside the area the app covers.

Source: US Census cartographic county boundaries (public domain), by FIPS.
The eight counties of the diocese are kept as separate simplified polygons —
a point inside any of them is inside the diocese — which avoids needing a
polygon-union library here and costs nothing at lookup time.

Why not "distance to the nearest parish": neighbouring dioceses put parishes
within a few miles of ours (Stow is ours, Kent five miles away is Youngstown),
while rural corners of our own counties sit 25+ miles from the nearest parish
in our data. No radius separates the two cases.

Usage:  python3 tool/gen_diocese_boundary.py [path/to/counties.geojson]
Never hand-edit the generated JSON; re-run this instead.
"""

import json
import math
import os
import sys
import urllib.request

SOURCE_URL = (
    'https://raw.githubusercontent.com/plotly/datasets/master/'
    'geojson-counties-fips.json'
)

# The eight counties of the Diocese of Cleveland, by state+county FIPS.
DIOCESE_FIPS = {
    '39005': 'Ashland',
    '39035': 'Cuyahoga',
    '39055': 'Geauga',
    '39085': 'Lake',
    '39093': 'Lorain',
    '39103': 'Medina',
    '39153': 'Summit',
    '39169': 'Wayne',
}

# Douglas-Peucker tolerance in degrees. ~0.002° is roughly 200 m here, which
# is far finer than "which diocese are you in" needs while keeping the asset
# small enough to bundle.
TOLERANCE = 0.002
PRECISION = 4  # ~11 m


def perpendicular_distance(pt, start, end):
    if start == end:
        return math.dist(pt, start)
    x0, y0 = pt
    x1, y1 = start
    x2, y2 = end
    num = abs((y2 - y1) * x0 - (x2 - x1) * y0 + x2 * y1 - y2 * x1)
    return num / math.dist(start, end)


def simplify(points, tolerance):
    """Iterative Douglas-Peucker — recursion overflows on county-sized rings."""
    if len(points) < 3:
        return list(points)
    keep = [False] * len(points)
    keep[0] = keep[-1] = True
    stack = [(0, len(points) - 1)]
    while stack:
        first, last = stack.pop()
        if last <= first + 1:
            continue
        worst, worst_i = 0.0, first
        for i in range(first + 1, last):
            d = perpendicular_distance(points[i], points[first], points[last])
            if d > worst:
                worst, worst_i = d, i
        if worst > tolerance:
            keep[worst_i] = True
            stack.append((first, worst_i))
            stack.append((worst_i, last))
    return [p for p, k in zip(points, keep) if k]


def rings_of(geometry):
    """Every outer ring of a Polygon or MultiPolygon, as [(lon, lat), ...]."""
    if geometry['type'] == 'Polygon':
        return [geometry['coordinates'][0]]
    if geometry['type'] == 'MultiPolygon':
        return [poly[0] for poly in geometry['coordinates']]
    raise ValueError(f"unexpected geometry {geometry['type']}")


def main():
    if len(sys.argv) > 1:
        with open(sys.argv[1]) as handle:
            source = json.load(handle)
    else:
        print(f'Downloading {SOURCE_URL} …')
        with urllib.request.urlopen(SOURCE_URL) as response:
            source = json.load(response)

    found = {}
    for feature in source['features']:
        fips = feature.get('id') or feature['properties'].get('GEO_ID', '')[-5:]
        if fips in DIOCESE_FIPS:
            found[fips] = feature

    missing = set(DIOCESE_FIPS) - set(found)
    if missing:
        raise SystemExit(f'missing counties in source data: {sorted(missing)}')

    polygons = []
    raw_points = simplified_points = 0
    for fips, name in sorted(DIOCESE_FIPS.items(), key=lambda kv: kv[1]):
        for ring in rings_of(found[fips]['geometry']):
            ring = [(float(x), float(y)) for x, y in ring]
            raw_points += len(ring)
            small = simplify(ring, TOLERANCE)
            # A ring simplified below a triangle encloses no area; drop it.
            if len(small) < 4:
                continue
            simplified_points += len(small)
            # Stored [lat, lon] to match how the app carries coordinates.
            polygons.append(
                [[round(lat, PRECISION), round(lon, PRECISION)]
                 for lon, lat in small]
            )

    out = {
        '_comment': (
            'Generated by tool/gen_diocese_boundary.py from US Census '
            'cartographic county boundaries (public domain). Do not hand-edit.'
        ),
        'diocese': 'Diocese of Cleveland',
        'counties': sorted(DIOCESE_FIPS.values()),
        'toleranceDegrees': TOLERANCE,
        'polygons': polygons,
    }

    target = os.path.join('assets', 'data', 'diocese_boundary.json')
    os.makedirs(os.path.dirname(target), exist_ok=True)
    with open(target, 'w') as handle:
        json.dump(out, handle, separators=(',', ':'))
        handle.write('\n')

    print(f'{len(polygons)} polygons, {raw_points} → {simplified_points} points')
    print(f'wrote {target} ({os.path.getsize(target) / 1024:.1f} KB)')


if __name__ == '__main__':
    main()
